CREATE TABLE IF NOT EXISTS users(
  id INTEGER NOT NULL PRIMARY KEY,
  username TEXT NOT NULL,
  password BLOB NOT NULL,
  salt BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS posts(
  id INTEGER NOT NULL PRIMARY KEY,
  author INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  date INTEGER NOT NULL,
  FOREIGN KEY (author) REFERENCES users (id)
);